### ISSUE TITLE
Add Support for Netbox >=3.6.0

### ISSUE THREAD

**Issue by felixosp** [k01ek/netbox-bgp#151]
installing the plugin with 
> manage.py collectstatic 

fails with:
```
1.503 Traceback (most recent call last):
1.503   File "/opt/netbox/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 255, in fetch_command
1.503     app_name = commands[subcommand]
1.503                ~~~~~~~~^^^^^^^^^^^^
1.503 KeyError: 'trace_paths'
1.503 
1.503 During handling of the above exception, another exception occurred:
1.503 
1.503 Traceback (most recent call last):
1.504   File "/opt/netbox/netbox/manage.py", line 10, in <module>
1.504     execute_from_command_line(sys.argv)
1.504   File "/opt/netbox/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
1.504     utility.execute()
1.504   File "/opt/netbox/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
1.504     self.fetch_command(subcommand).run_from_argv(self.argv)
1.504     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
1.504   File "/opt/netbox/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 262, in fetch_command
1.504     settings.INSTALLED_APPS
1.504   File "/opt/netbox/venv/lib/python3.11/site-packages/django/conf/__init__.py", line 102, in __getattr__
1.504     self._setup(name)
1.504   File "/opt/netbox/venv/lib/python3.11/site-packages/django/conf/__init__.py", line 89, in _setup
1.504     self._wrapped = Settings(settings_module)
1.504                     ^^^^^^^^^^^^^^^^^^^^^^^^^
1.504   File "/opt/netbox/venv/lib/python3.11/site-packages/django/conf/__init__.py", line 217, in __init__
1.504     mod = importlib.import_module(self.SETTINGS_MODULE)
1.504           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
1.504   File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
1.504     return _bootstrap._gcd_import(name[level:], package, level)
1.504            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
1.504   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
1.504   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
1.504   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
1.504   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
1.504   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
1.504   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
1.504   File "/opt/netbox/netbox/netbox/settings.py", line 778, in <module>
1.504     plugin_config.validate(PLUGINS_CONFIG[plugin_name], VERSION)
1.504   File "/opt/netbox/netbox/extras/plugins/__init__.py", line 133, in validate
1.504     raise ImproperlyConfigured(
1.504 django.core.exceptions.ImproperlyConfigured: Plugin netbox_bgp requires NetBox maximum version 3.5.99.
```

**Comment by balpoint** [comment]
for now i've tested it with the 3.6 update and it seems to be running fine without any issues so far. 

What you could do as a workaround is the following:

- Make sure you remove the plugin from the configuration.py file
- Enter the venv environment 
`source /opt/netbox/venv/bin/activate`
- Install the plugin seperatly
`pip install netbox-bgp`
- Go to the netbox_bgp package location
`cd /opt/netbox/venv/lib/python3.8/site-packages/netbox_bgp/`
- Edit the file __init__.py
- Change the max version to 3.6.99 ( or something else but at least 3.6.0)
- Enable the plugin in the configuration.py
- Exit the venv 
`deactivate`
- Reload netbox
`sudo systemctl restart netbox netbox-rq`

**Comment by Kani999** [comment]
Opened PR #152
