### ISSUE TITLE
Error import TagFilter from utilities.filters

### ISSUE THREAD

**Issue by donatid** [k01ek/netbox-bgp#27]
Hi,
I found this error when trying to enable netbox-bgp

Netbox version v2.11.4-dev

1. cd /opt/netbox
2. source venv/bin/activate
3. cd /opt/netbox/netbox
4. run ./manage.py runserver 0.0.0.0:8000 --insecure

Error log:
```
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/netbox/venv/lib64/python3.8/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/opt/netbox/venv/lib64/python3.8/site-packages/django/core/management/commands/runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "/opt/netbox/venv/lib64/python3.8/site-packages/django/core/management/base.py", line 419, in check
    all_issues = checks.run_checks(
  File "/opt/netbox/venv/lib64/python3.8/site-packages/django/core/checks/registry.py", line 76, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/opt/netbox/venv/lib64/python3.8/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/opt/netbox/venv/lib64/python3.8/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/opt/netbox/venv/lib64/python3.8/site-packages/django/urls/resolvers.py", line 412, in check
    for pattern in self.url_patterns:
  File "/opt/netbox/venv/lib64/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/netbox/venv/lib64/python3.8/site-packages/django/urls/resolvers.py", line 598, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/opt/netbox/venv/lib64/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/opt/netbox/venv/lib64/python3.8/site-packages/django/urls/resolvers.py", line 591, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/netbox/netbox/netbox/urls.py", line 8, in <module>
    from extras.plugins.urls import plugin_admin_patterns, plugin_patterns, plugin_api_patterns
  File "/opt/netbox/netbox/extras/plugins/urls.py", line 35, in <module>
    urlpatterns = import_object(f"{plugin_path}.api.urls.urlpatterns")
  File "/opt/netbox/netbox/extras/plugins/utils.py", line 31, in import_object
    spec.loader.exec_module(module)
  File "/opt/netbox/venv/lib64/python3.8/site-packages/netbox_bgp/api/urls.py", line 3, in <module>
    from .views import ASNViewSet, BGPSessionViewSet, RoutingPolicyViewSet
  File "/opt/netbox/venv/lib64/python3.8/site-packages/netbox_bgp/api/views.py", line 5, in <module>
    from netbox_bgp.filters import ASNFilterSet, BGPSessionFilterSet, RoutingPolicyFilterSet
  File "/opt/netbox/venv/lib64/python3.8/site-packages/netbox_bgp/filters.py", line 4, in <module>
    from utilities.filters import TagFilter
ImportError: cannot import name 'TagFilter' from 'utilities.filters' (/opt/netbox/netbox/utilities/filters.py)
```
Temporary fix:

Change line number 4 in the netbox_bgp/filters.py
`from utilities.filters import TagFilter`
to 
`from extras.filters import TagFilter`

And rerun the server:

```
./manage.py runserver 0.0.0.0:8000 --insecure
Performing system checks...

System check identified no issues (0 silenced).

You have 15 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): netbox_bgp.
Run 'python manage.py migrate' to apply them.
May 09, 2021 - 18:19:50
Django version 3.2.2, using settings 'netbox.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.

```

Thank you

**Comment by omri-ice** [comment]
This applies to Netbox [v2.11.3](https://github.com/netbox-community/netbox/commit/d35ac1347cebd46740188f1b294ac50499f3c1ea#diff-7ebd9bfe55d54b7bea53b4fa0099b14247fcf7d0eaf7417d247b8a1885048e08), the fix to support both v2.11.3 and newer as well as versions 2.11.2 and lower would be similar to this:
 on [`filters.py`](https://github.com/k01ek/netbox-bgp/blob/cdca172527370bc05603962384618feebfd09b8e/netbox_bgp/filters.py#L4) line 4
```python
try:
    from extras.filters import TagFilter
except ImportError:
    from utilities.filters import TagFilter
```
