### ISSUE TITLE
Netbox BGP ModuleNotFoundError

### ISSUE THREAD

**Issue by jbparrish17** [k01ek/netbox-bgp#8]
Hello,

Attempting to install this plugin on a fresh install of Netbox on Ubuntu 20.04 LTS. I have Python 3.8.5 installed and have installed the plugin with pip3 after activating the netbox virtual environment:
`sudo pip3 install netbox_bgp`

I've added the plugin 'netbox_bgp' to the plugins list in configuration.py but when I restart the netbox service I am met with the following:

`ModuleNotFoundError: No module named 'netbox_bgp'`

When I attempt to reinstall netbox-bgp, pip3 says the requirement is already met:
`Requirement already satisfied: netbox-bgp in /usr/local/lib/python3.8/dist-packages (0.1.0)`

Am I installing this incorrectly or is there a dependency that I might be missing?

**Comment by k01ek** [comment]
Hi @jbparrish17 ! You need to install the plugin with in virtual environment that netbox uses. Something like that: 
`sudo /opt/netbox/venv/bin/pip3 install netbox-bgp` 
You can find this way in documentation https://netbox.readthedocs.io/en/stable/plugins/

**Comment by jbparrish17** [comment]
Thanks for the reply. Yes, I have added the plugin within the virtual environment. Seemed to be a permissions issue. I successfully reinstalled using the update.sh script available in the netbox project. However, I now receive the following error when the 'netbox_bgp' plugin is enabled in configuration.py

`Traceback (most recent call last):
  File "netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/opt/netbox/venv/lib/python3.8/site-packages/django/apps/config.py", line 301, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/netbox/venv/lib/python3.8/site-packages/netbox_bgp/models.py", line 8, in <module>
    from extras.models import ChangeLoggedModel, TaggedItem
ImportError: cannot import name 'ChangeLoggedModel' from 'extras.models' (/opt/netbox/netbox/extras/models/__init__.py)`

**Comment by k01ek** [comment]
I have not tested yet the plugin with netbox 2.11,  it's looks like the plugin is  incompatible with new version

**Comment by vladsker** [comment]
I'm also having an issue in 2.11.0:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox/venv/lib64/python3.6/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/opt/netbox/venv/lib64/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/opt/netbox/venv/lib64/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/netbox/venv/lib64/python3.6/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/opt/netbox/venv/lib64/python3.6/site-packages/django/apps/config.py", line 301, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/netbox/venv/lib64/python3.6/site-packages/netbox_bgp/models.py", line 8, in <module>
    from extras.models import ChangeLoggedModel, TaggedItem
ImportError: cannot import name 'ChangeLoggedModel'

**Comment by k01ek** [comment]
fixed

**Comment by vladsker** [comment]
Thanks a lot. You're doing a great job!

I'm going to test it later today.
